### ISSUE TITLE
Italian number formatting

### ISSUE THREAD

**Issue by Sesam31** [SimpleMobileTools/Simple-Calculator#250] opened 2022-03-25 06:44 UTC
Hi, I've been using the app for quite a while but I was always bothered by the english number formatting.
Here is an example of english and italian number formatting:
Italian              | 4.294.967.295,000
GB-English     | 4,294,967,295.00
Can this be implemented? 
While looking around on the intenet I also found this table that might be useful for formatting numbers in many different languages:
https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

**Comment by tibbi** [comment] 2022-03-25 08:07
duplicate of #96

**Closed by tibbi** 2022-03-25 08:07 UTC
