### ISSUE TITLE
"Purchase Simple Thank You" bug?

### ISSUE THREAD

**Issue by dhammel** [SimpleMobileTools/Simple-Calculator#181] opened 2020-10-10 11:02 UTC
Hello,

After upgrading to android 11, this error happened (didn't occur on android 10), it displays Purchase simple Thank You at top of settings, with shared theme not working.

This same issue occurs with Clock and Voice Recorder, however it does not occur with Gallery, Calendar, or dialer. As for other simple apps, i dont know.

I have tried uninstall, reboot and reinstall of both the app and the thank you app. I have installed the latest version availible of each from Fdroid, stable versions.

I have a pixel 4, android 11 october update.

**Comment by tibbi** [comment] 2020-10-10 17:59
Hey, not sure what is the issue here. The not working Shared theme?

**Comment by dhammel** [comment] 2020-10-10 19:07
Yes, the non-working shared theme. Basically its as if the apps are not detecting the thank you app as being installed

**Comment by tibbi** [comment] 2020-10-10 20:32
but if you go into the app settings -> customize colors in some apps, you cannot even pick Shared theme?

**Comment by dhammel** [comment] 2020-10-10 20:42
That's correct. Shared theme is not an option.

**Comment by tibbi** [comment] 2020-10-10 20:51
did you get Simple Thank You from Google Play, or some other source?

**Comment by dhammel** [comment] 2020-10-10 20:53
I purchased it from google play to support you, but installed from fdroid. It was working previously, on android 10.

**Comment by dhammel** [comment] 2020-10-11 04:43
I just tested the versions of the calculator and thank you app both from google play and issue still occurs. Same issue with other mentioned apps, even with google play versions. Its probably some issue with android 11

**Comment by tibbi** [comment] 2020-12-28 19:25
it seems to be caused by a new Android 11 security feature, with which apps cannot detect what other apps are installed. It is already fixed in some apps, will be added into calculator in 5.5.0

**Closed by tibbi** 2020-12-28 19:25 UTC
Labels: bug

**Comment by dhammel** [comment] 2020-12-28 19:44
Oh, thats interesting. Well if it is a security feature, that it just cannot detect the thank you app then how would you be 'fixing' it?

**Comment by tibbi** [comment] 2020-12-28 20:15
by requesting the QUERY_ALL_PACKAGES permission, all apps from our suite will need it. It will be needed for other communication between apps too, like sharing contacts between Contacts and Dialer etc.
