### ISSUE TITLE
Number replaces 0 after using the x operator

### ISSUE THREAD

**Issue by ynsnf** [SimpleMobileTools/Simple-Calculator#235] opened 2022-01-08 13:13 UTC
### Steps to Reproduce the bug

1. Multiply Any Number 

![Screenshot_20220108-181427_Calculator](https://user-images.githubusercontent.com/95400016/148645027-26ee3de2-6a4c-40ac-9db2-73d551aae147.jpg)

2. Use the x operator and it replaces that number with 0

![Screenshot_20220108-181431_Calculator](https://user-images.githubusercontent.com/95400016/148645033-ba9a2f14-5262-47f5-ba38-720314cf93e4.jpg)

Note: After Update 5.4.3

**Comment by Aga-C** [comment] 2022-01-09 13:28
Are you using `C` button meanwhile? Because I've found a bit similar bug. Here are reproduction steps:

1. Write a formula like `3x5`
2. Press `C` button as many times to just leave the first number (in this example 3)
3. Press any operator button (e.g. `x`)

As a result, instead of having a formula like `3x` I get a `3x0` and below a formula `0x`.

**Comment by ynsnf** [comment] 2022-01-09 15:08
@Aga-C Yes . I tried this and found the same bug.

**Comment by tibbi** [comment] 2022-02-11 19:54
so guess this was fixed with the mentioned PR

**Closed by tibbi** 2022-02-11 19:54 UTC
