### ISSUE TITLE
[Feature Request] Option to disable comma, dot between 1000

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Calculator#313] opened 2023-07-30 21:42 UTC
![image](https://github.com/SimpleMobileTools/Simple-Calculator/assets/75314629/3297b736-cfee-4eb5-b344-af62c9980adb)

**Comment by Aga-C** [comment] 2023-07-31 03:57
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calculator/issues/292.

**Closed** 2023-07-31 07:56 UTC
Labels: feature request
